url: https://nexusheights.org
baseurl: /

# Site settings
title: Nexus Heights
email: nexusheights@gmail.com
description: "A small mobile apps startup headquartered and founded in Rogersville, TN."


# Team names, titles and social links
people:
- name: Hunter Stanton
  pic: 1
  position: Co-Founder / Lead iOS Developer
  social:
    - title: twitter
      url: http://twitter.com/hunter_stanton
    - title: github
      url: http://github.com/HunterStanton

- name: Drew Michel
  pic: 2
  position: Co-Founder
  social:
    - title: twitter
      url: http://twitter.com/drew_michel


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/nexus_heights
  - title: github
    url: http://github.com/nexusheights
  - title: instagram
    url: http://instagram.com/nexus_heights

# Build settings
markdown: kramdown
permalink: pretty